source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
inhibit_all_warnings!

def shared_pods
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper'
  pod 'SDWebImage', '~> 5.0'
  pod 'SkeletonView', '1.4.2'
  pod 'Actions', '3.0.1'
end

target 'AnimeProject' do
	use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
