source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

def shared_pods
  pod 'CocoaDebug', '1.6.0'
  pod 'FSPagerView', '0.8.3'
end

target 'AnimeProject' do
	use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
